dshUI: Refactored themeing logic, code clean up, minor bug fixes. All manual dshUI tests passed. This commit is related to issue #28.

diff --git a/dshUI/dshUI b/dshUI/dshUI
--- a/dshUI/dshUI
+++ b/dshUI/dshUI
@@ -3,103 +3,120 @@
 set -o posix
 
 demoTheme() {
+    clear
     printf "\n%sNORMAL_TEXT" "${NORMAL_TEXT}"
     printf "\n%sBOLD_TEXT" "${BOLD_TEXT}"
     printf "\n%sUNDERLINED_TEXT" "${UNDERLINED_TEXT}"
     printf "\n%sBLINKING_TEXT" "${BLINKING_TEXT}"
     printf "\n%sREVERSE_TEXT" "${REVERSE_TEXT}"
 
-    printf "\n%sNORMAL_COLOR 1" "${NORMAL_COLOR_1}"
-    printf "\n%sNORMAL_COLOR 2" "${NORMAL_COLOR_2}"
-    printf "\n%sNORMAL_COLOR 3" "${NORMAL_COLOR_3}"
-    printf "\n%sNORMAL_COLOR 4" "${NORMAL_COLOR_4}"
-    printf "\n%sNORMAL_COLOR 5" "${NORMAL_COLOR_5}"
-    printf "\n%sNORMAL_COLOR 6" "${NORMAL_COLOR_6}"
-    printf "\n%sNORMAL_COLOR 7" "${NORMAL_COLOR_7}"
-    printf "\n%sNORMAL_COLOR 8" "${NORMAL_COLOR_8}"
-    printf "\n%sNORMAL_COLOR 9" "${NORMAL_COLOR_9}"
-    printf "\n%sNORMAL_COLOR 10" "${NORMAL_COLOR_10}"
-    printf "\n%sNORMAL_COLOR 11" "${NORMAL_COLOR_12}"
-    printf "\n%sNORMAL_COLOR 12" "${NORMAL_COLOR_12}"
-    printf "\n%sNORMAL_COLOR 13" "${NORMAL_COLOR_13}"
-    printf "\n%sNORMAL_COLOR 14" "${NORMAL_COLOR_14}"
-    printf "\n%sNORMAL_COLOR 15" "${NORMAL_COLOR_15}"
-    printf "\n%sNORMAL_COLOR 16" "${NORMAL_COLOR_16}"
+    printf "\n%sNORMAL_COLOR_1" "${NORMAL_COLOR_1}"
+    printf "\n%sNORMAL_COLOR_2" "${NORMAL_COLOR_2}"
+    printf "\n%sNORMAL_COLOR_3" "${NORMAL_COLOR_3}"
+    printf "\n%sNORMAL_COLOR_4" "${NORMAL_COLOR_4}"
+    printf "\n%sNORMAL_COLOR_5" "${NORMAL_COLOR_5}"
+    printf "\n%sNORMAL_COLOR_6" "${NORMAL_COLOR_6}"
+    printf "\n%sNORMAL_COLOR_7" "${NORMAL_COLOR_7}"
+    printf "\n%sNORMAL_COLOR_8" "${NORMAL_COLOR_8}"
+    printf "\n%sNORMAL_COLOR_9" "${NORMAL_COLOR_9}"
+    printf "\n%sNORMAL_COLOR_10" "${NORMAL_COLOR_10}"
+    printf "\n%sNORMAL_COLOR_11" "${NORMAL_COLOR_12}"
+    printf "\n%sNORMAL_COLOR_12" "${NORMAL_COLOR_12}"
+    printf "\n%sNORMAL_COLOR_13" "${NORMAL_COLOR_13}"
+    printf "\n%sNORMAL_COLOR_14" "${NORMAL_COLOR_14}"
+    printf "\n%sNORMAL_COLOR_15" "${NORMAL_COLOR_15}"
+    printf "\n%sNORMAL_COLOR_16" "${NORMAL_COLOR_16}"
 
-    printf "\n%sBOLD_COLOR 1" "${BOLD_COLOR_1}"
-    printf "\n%sBOLD_COLOR 2" "${BOLD_COLOR_2}"
-    printf "\n%sBOLD_COLOR 3" "${BOLD_COLOR_3}"
-    printf "\n%sBOLD_COLOR 4" "${BOLD_COLOR_4}"
-    printf "\n%sBOLD_COLOR 5" "${BOLD_COLOR_5}"
-    printf "\n%sBOLD_COLOR 6" "${BOLD_COLOR_6}"
-    printf "\n%sBOLD_COLOR 7" "${BOLD_COLOR_7}"
-    printf "\n%sBOLD_COLOR 8" "${BOLD_COLOR_8}"
-    printf "\n%sBOLD_COLOR 9" "${BOLD_COLOR_9}"
-    printf "\n%sBOLD_COLOR 10" "${BOLD_COLOR_10}"
-    printf "\n%sBOLD_COLOR 11" "${BOLD_COLOR_12}"
-    printf "\n%sBOLD_COLOR 12" "${BOLD_COLOR_12}"
-    printf "\n%sBOLD_COLOR 13" "${BOLD_COLOR_13}"
-    printf "\n%sBOLD_COLOR 14" "${BOLD_COLOR_14}"
-    printf "\n%sBOLD_COLOR 15" "${BOLD_COLOR_15}"
-    printf "\n%sBOLD_COLOR 16" "${BOLD_COLOR_16}"
+    printf "\n%sBOLD_COLOR_1" "${BOLD_COLOR_1}"
+    printf "\n%sBOLD_COLOR_2" "${BOLD_COLOR_2}"
+    printf "\n%sBOLD_COLOR_3" "${BOLD_COLOR_3}"
+    printf "\n%sBOLD_COLOR_4" "${BOLD_COLOR_4}"
+    printf "\n%sBOLD_COLOR_5" "${BOLD_COLOR_5}"
+    printf "\n%sBOLD_COLOR_6" "${BOLD_COLOR_6}"
+    printf "\n%sBOLD_COLOR_7" "${BOLD_COLOR_7}"
+    printf "\n%sBOLD_COLOR_8" "${BOLD_COLOR_8}"
+    printf "\n%sBOLD_COLOR_9" "${BOLD_COLOR_9}"
+    printf "\n%sBOLD_COLOR_10" "${BOLD_COLOR_10}"
+    printf "\n%sBOLD_COLOR_11" "${BOLD_COLOR_12}"
+    printf "\n%sBOLD_COLOR_12" "${BOLD_COLOR_12}"
+    printf "\n%sBOLD_COLOR_13" "${BOLD_COLOR_13}"
+    printf "\n%sBOLD_COLOR_14" "${BOLD_COLOR_14}"
+    printf "\n%sBOLD_COLOR_15" "${BOLD_COLOR_15}"
+    printf "\n%sBOLD_COLOR_16" "${BOLD_COLOR_16}"
 
-    printf "\n%sUNDERLINED_COLOR 1" "${UNDERLINED_COLOR_1}"
-    printf "\n%sUNDERLINED_COLOR 2" "${UNDERLINED_COLOR_2}"
-    printf "\n%sUNDERLINED_COLOR 3" "${UNDERLINED_COLOR_3}"
-    printf "\n%sUNDERLINED_COLOR 4" "${UNDERLINED_COLOR_4}"
-    printf "\n%sUNDERLINED_COLOR 5" "${UNDERLINED_COLOR_5}"
-    printf "\n%sUNDERLINED_COLOR 6" "${UNDERLINED_COLOR_6}"
-    printf "\n%sUNDERLINED_COLOR 7" "${UNDERLINED_COLOR_7}"
-    printf "\n%sUNDERLINED_COLOR 8" "${UNDERLINED_COLOR_8}"
-    printf "\n%sUNDERLINED_COLOR 9" "${UNDERLINED_COLOR_9}"
-    printf "\n%sUNDERLINED_COLOR 10" "${UNDERLINED_COLOR_10}"
-    printf "\n%sUNDERLINED_COLOR 11" "${UNDERLINED_COLOR_12}"
-    printf "\n%sUNDERLINED_COLOR 12" "${UNDERLINED_COLOR_12}"
-    printf "\n%sUNDERLINED_COLOR 13" "${UNDERLINED_COLOR_13}"
-    printf "\n%sUNDERLINED_COLOR 14" "${UNDERLINED_COLOR_14}"
-    printf "\n%sUNDERLINED_COLOR 15" "${UNDERLINED_COLOR_15}"
-    printf "\n%sUNDERLINED_COLOR 16" "${UNDERLINED_COLOR_16}"
+    printf "\n%sUNDERLINED_COLOR_1" "${UNDERLINED_COLOR_1}"
+    printf "\n%sUNDERLINED_COLOR_2" "${UNDERLINED_COLOR_2}"
+    printf "\n%sUNDERLINED_COLOR_3" "${UNDERLINED_COLOR_3}"
+    printf "\n%sUNDERLINED_COLOR_4" "${UNDERLINED_COLOR_4}"
+    printf "\n%sUNDERLINED_COLOR_5" "${UNDERLINED_COLOR_5}"
+    printf "\n%sUNDERLINED_COLOR_6" "${UNDERLINED_COLOR_6}"
+    printf "\n%sUNDERLINED_COLOR_7" "${UNDERLINED_COLOR_7}"
+    printf "\n%sUNDERLINED_COLOR_8" "${UNDERLINED_COLOR_8}"
+    printf "\n%sUNDERLINED_COLOR_9" "${UNDERLINED_COLOR_9}"
+    printf "\n%sUNDERLINED_COLOR_10" "${UNDERLINED_COLOR_10}"
+    printf "\n%sUNDERLINED_COLOR_11" "${UNDERLINED_COLOR_12}"
+    printf "\n%sUNDERLINED_COLOR_12" "${UNDERLINED_COLOR_12}"
+    printf "\n%sUNDERLINED_COLOR_13" "${UNDERLINED_COLOR_13}"
+    printf "\n%sUNDERLINED_COLOR_14" "${UNDERLINED_COLOR_14}"
+    printf "\n%sUNDERLINED_COLOR_15" "${UNDERLINED_COLOR_15}"
+    printf "\n%sUNDERLINED_COLOR_16" "${UNDERLINED_COLOR_16}"
 
-    printf "\n%sBLINKING_COLOR 1" "${BLINKING_COLOR_1}"
-    printf "\n%sBLINKING_COLOR 2" "${BLINKING_COLOR_2}"
-    printf "\n%sBLINKING_COLOR 3" "${BLINKING_COLOR_3}"
-    printf "\n%sBLINKING_COLOR 4" "${BLINKING_COLOR_4}"
-    printf "\n%sBLINKING_COLOR 5" "${BLINKING_COLOR_5}"
-    printf "\n%sBLINKING_COLOR 6" "${BLINKING_COLOR_6}"
-    printf "\n%sBLINKING_COLOR 7" "${BLINKING_COLOR_7}"
-    printf "\n%sBLINKING_COLOR 8" "${BLINKING_COLOR_8}"
-    printf "\n%sBLINKING_COLOR 9" "${BLINKING_COLOR_9}"
-    printf "\n%sBLINKING_COLOR 10" "${BLINKING_COLOR_10}"
-    printf "\n%sBLINKING_COLOR 11" "${BLINKING_COLOR_12}"
-    printf "\n%sBLINKING_COLOR 12" "${BLINKING_COLOR_12}"
-    printf "\n%sBLINKING_COLOR 13" "${BLINKING_COLOR_13}"
-    printf "\n%sBLINKING_COLOR 14" "${BLINKING_COLOR_14}"
-    printf "\n%sBLINKING_COLOR 15" "${BLINKING_COLOR_15}"
-    printf "\n%sBLINKING_COLOR 16" "${BLINKING_COLOR_16}"
+    printf "\n%sBLINKING_COLOR_1" "${BLINKING_COLOR_1}"
+    printf "\n%sBLINKING_COLOR_2" "${BLINKING_COLOR_2}"
+    printf "\n%sBLINKING_COLOR_3" "${BLINKING_COLOR_3}"
+    printf "\n%sBLINKING_COLOR_4" "${BLINKING_COLOR_4}"
+    printf "\n%sBLINKING_COLOR_5" "${BLINKING_COLOR_5}"
+    printf "\n%sBLINKING_COLOR_6" "${BLINKING_COLOR_6}"
+    printf "\n%sBLINKING_COLOR_7" "${BLINKING_COLOR_7}"
+    printf "\n%sBLINKING_COLOR_8" "${BLINKING_COLOR_8}"
+    printf "\n%sBLINKING_COLOR_9" "${BLINKING_COLOR_9}"
+    printf "\n%sBLINKING_COLOR_10" "${BLINKING_COLOR_10}"
+    printf "\n%sBLINKING_COLOR_11" "${BLINKING_COLOR_12}"
+    printf "\n%sBLINKING_COLOR_12" "${BLINKING_COLOR_12}"
+    printf "\n%sBLINKING_COLOR_13" "${BLINKING_COLOR_13}"
+    printf "\n%sBLINKING_COLOR_14" "${BLINKING_COLOR_14}"
+    printf "\n%sBLINKING_COLOR_15" "${BLINKING_COLOR_15}"
+    printf "\n%sBLINKING_COLOR_16" "${BLINKING_COLOR_16}"
 
-    printf "\n%sREVERSE_COLOR 1" "${REVERSE_COLOR_1}"
-    printf "\n%sREVERSE_COLOR 2" "${REVERSE_COLOR_2}"
-    printf "\n%sREVERSE_COLOR 3" "${REVERSE_COLOR_3}"
-    printf "\n%sREVERSE_COLOR 4" "${REVERSE_COLOR_4}"
-    printf "\n%sREVERSE_COLOR 5" "${REVERSE_COLOR_5}"
-    printf "\n%sREVERSE_COLOR 6" "${REVERSE_COLOR_6}"
-    printf "\n%sREVERSE_COLOR 7" "${REVERSE_COLOR_7}"
-    printf "\n%sREVERSE_COLOR 8" "${REVERSE_COLOR_8}"
-    printf "\n%sREVERSE_COLOR 9" "${REVERSE_COLOR_9}"
-    printf "\n%sREVERSE_COLOR 10" "${REVERSE_COLOR_10}"
-    printf "\n%sREVERSE_COLOR 11" "${REVERSE_COLOR_12}"
-    printf "\n%sREVERSE_COLOR 12" "${REVERSE_COLOR_12}"
-    printf "\n%sREVERSE_COLOR 13" "${REVERSE_COLOR_13}"
-    printf "\n%sREVERSE_COLOR 14" "${REVERSE_COLOR_14}"
-    printf "\n%sREVERSE_COLOR 15" "${REVERSE_COLOR_15}"
-    printf "\n%sREVERSE_COLOR 16" "${REVERSE_COLOR_16}"
+    printf "\n%sREVERSE_COLOR_1" "${REVERSE_COLOR_1}"
+    printf "\n%sREVERSE_COLOR_2" "${REVERSE_COLOR_2}"
+    printf "\n%sREVERSE_COLOR_3" "${REVERSE_COLOR_3}"
+    printf "\n%sREVERSE_COLOR_4" "${REVERSE_COLOR_4}"
+    printf "\n%sREVERSE_COLOR_5" "${REVERSE_COLOR_5}"
+    printf "\n%sREVERSE_COLOR_6" "${REVERSE_COLOR_6}"
+    printf "\n%sREVERSE_COLOR_7" "${REVERSE_COLOR_7}"
+    printf "\n%sREVERSE_COLOR_8" "${REVERSE_COLOR_8}"
+    printf "\n%sREVERSE_COLOR_9" "${REVERSE_COLOR_9}"
+    printf "\n%sREVERSE_COLOR_10" "${REVERSE_COLOR_10}"
+    printf "\n%sREVERSE_COLOR_11" "${REVERSE_COLOR_12}"
+    printf "\n%sREVERSE_COLOR_12" "${REVERSE_COLOR_12}"
+    printf "\n%sREVERSE_COLOR_13" "${REVERSE_COLOR_13}"
+    printf "\n%sREVERSE_COLOR_14" "${REVERSE_COLOR_14}"
+    printf "\n%sREVERSE_COLOR_15" "${REVERSE_COLOR_15}"
+    printf "\n%sREVERSE_COLOR_16" "${REVERSE_COLOR_16}"
+
+
+    printf "${NORMAL_TEXT}"
+    printf "${NORMAL_TEXT}"
+    printf "${NORMAL_TEXT}"
+    printf "${NORMAL_TEXT}"
+    printf "${NORMAL_TEXT}"
 }
 
 setTextStyleCode() {
   printf "\e[%sm" "${1}"
 }
 
-setupPaths() {
+logErrorMsg() {
+    printf "\n%s%s\n%s" "$(setTextStyleCode 33)" "${1}" "$(setTextStyleCode 0)" >> /dev/stderr
+}
+
+logErrorMsgAndExit1() {
+    logErrorMsg "${1}"
+    exit 1
+}
+
+determineCurrentDirectoryPath() {
     local CURRENT_FILE_PATH CURRENT_DIRECTORY_PATH
     CURRENT_FILE_PATH="${BASH_SOURCE[0]}"
     while [ -h "$CURRENT_FILE_PATH" ]; do # resolve $CURRENT_FILE_PATH until the file is no longer a symlink | -h is true if file exists and is a symlink
@@ -107,43 +124,58 @@ setupPaths() {
       CURRENT_FILE_PATH="$(readlink "$CURRENT_FILE_PATH")"
       [[ $CURRENT_FILE_PATH != /* ]] && CURRENT_FILE_PATH="$CURRENT_DIRECTORY_PATH/$CURRENT_FILE_PATH" # if $CURRENT_FILE_PATH was a relative symlink, we need to resolve it relative to the path where the symlink file was located
     done
-    PATH_TO_DSHUI_DIR="$(cd -P "$(dirname "$CURRENT_FILE_PATH")" >/dev/null 2>&1 && pwd)"
-    PATH_TO_DDMS_DIR="${PATH_TO_DSHUI_DIR/\/dshUI/}"
+    printf "%s" "$(cd -P "$(dirname "$CURRENT_FILE_PATH")" >/dev/null 2>&1 && pwd)"
 }
 
 loadLibrary() {
     # use of -x instead of -f is intentinal, the file MUST exist and be executable
     # @seehttps://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Bash-Conditional-Expressions
-    [[ ! -x "${1}" ]] && printf "\n\n\e[33mError! Failed to load ${1}!\e[0m\n\n" && exit 1
+    [[ ! -x "${1}" ]] && logErrorMsg "Error! Failed to load ${1}!" && exit 1
     . "${1}"
 }
 
-setupPaths
+logInvalidFlagErrorAndExit1() {
+    logErrorMsg "Invalid flag ${1}"
+    logErrorMsgAndExit1 "dshUI accepts one flag, --theme, or -t for short. The --theme flag is used to specify an alternative theme file."
+}
 
-# Load specified theme, or default theme if specified theme does not exist or if a theme was not specified.
-# @todo Implement --theme flag, and shorthand -t
-loadLibrary "${PATH_TO_DSHUI_DIR}/dshUIThemes/dshUIDefaultTheme.sh"
+logMissingFlagArgumentErrorAndExit1() {
+    logErrorMsgAndExit1 "You must specify the ${1} when using the ${2} flag"
+}
+
+logFileDoesNotExistErrorAndExit1() {
+    logErrorMsgAndExit1 "The ${1} file either does not exist, or is not executable."
+}
+
+determineThemeFilePath() {
+    printf "%s" "$(determineCurrentDirectoryPath)/dshUIThemes/${1}"
+}
 
 while test $# -gt 0; do
   case "$1" in
   -h | --help)
     shift
-    printf "\n%sdshUI is a library that proivdes various functions for generating a themeable UI for command line utilities.\n" "${BOLD_COLOR_5}"
+    printf "\ndshUI is a library that proivdes various functions for generating a themeable UI for command line utilities.\n"
     exit 0
     ;;
   -t | --theme*)
     shift
-    [[ -z "${1}" ]] && printf "\n%sYou must specify the name of a theme file when using the --theme flag\n" "${BOLD_COLOR_2}" && exit 1
-    printf "\n%sUsing theme: %s\n" "${BOLD_COLOR_15}" "${1}"
-    exit 0
+    [[ -z "${1}" ]] && logMissingFlagArgumentErrorAndExit1 "name of the theme file" "--theme"
+    [[ -x "$(determineThemeFilePath "$1")" ]] || logFileDoesNotExistErrorAndExit1 "$(determineThemeFilePath "${1}")"
+    DSHUI_THEME="${1}"
     ;;
   *)
-    printf "\n%sInvalid flag %s\n" "${BOLD_COLOR_10}" "${1}"
-    printf "\n%sdshUI accepts one flag, --theme, or -t for short. The --theme flag is used to specify an alternative theme file.\n" "${BOLD_COLOR_10}"
-    exit 1
+    [[ -n "${DSHUI_THEME}" ]] && break
+    logInvalidFlagErrorAndExit1 "${1}"
     ;;
   esac
 done
 
+[[ -z "${DSHUI_THEME}" ]] && DSHUI_THEME='dshUIDefaultTheme.sh'
+# Load specified theme, or default theme if specified theme does not exist or if a theme was not specified.
+# @todo Implement --theme flag, and shorthand -t
+loadLibrary "$(determineThemeFilePath "${DSHUI_THEME}")"
+demoTheme | column
+printf "\n%sUsing theme: %s\n" "${BOLD_COLOR_15}" "${DSHUI_THEME}"
+exit 0
 
-demoTheme
